name = "osm-pmtiles"
main = "src/index.ts"
compatibility_date = "2022-10-18"

account_id = "2474ed8f7c1faa9128e865f45721a6bb"
workers_dev = false
route = { pattern = "tiles.geojson.app", custom_domain = true }
minify = false

[vars]
ALLOWED_ORIGINS = "http://localhost:5173,https://localhost:8787,https://geojson.app"
PUBLIC_HOSTNAME = "tiles.geojson.app"
# CACHE_MAX_AGE = 86400

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "pmtiles"
